### PR TITLE
gh-226: Add oracles for Ironsworn

### PR DESCRIPTION
**Pull request by e4z9**
Oracles / tables from the main Ironsworn rules.

### CODE REVIEW

**Comment by e4z9** [comment]
Licensing info https://www.ironswornrpg.com/licensing (info included in meta.yml):

This work is based on Ironsworn (found at www.ironswornrpg.com), created by Shawn Tomkin, and licensed for our use under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license  (creativecommons.org/licenses/by-nc-sa/4.0/).

**Comment by stevesea** [comment]
Thank you!

**Comment by stevesea** [comment]
It's a lot of buttons on one screen: 

Screen Shot 2021-06-15 at 12 23 23 AM

 At the moment... I'm thinking of introducing subgroups:
* characters - npc & goal, names
* locations - location & descriptor, settlement name 
* combat/narrative - (all the rest) 

I'm not familiar with Ironsworn, so I'm not sure what the best grouping might be. Are there some oracles that are mostly useful for solo play vs. group play? Or, ones that are used mostly for GM preparation rather than during a session?

**Comment by stevesea** [comment]
added a couple more tables from the PDF and added subgroups as above: 

characters: 
Screen Shot 2021-06-15 at 2 05 32 AM


locations: 
Screen Shot 2021-06-15 at 2 04 07 AM

narrative & combat: 
Screen Shot 2021-06-15 at 2 04 43 AM

**Comment by e4z9** [comment]
Thanks for taking this up! I failed to come up with a grouping, I think your suggestion isn't bad.

In the narrative & combat maybe put the "Pay the Price", "Harm", "Stress" and "Mystic Backlash" together, these are the "suffer" tables. Or maybe put them into another group

Inspiration:
- Ask the Oracle
- Action & Theme
- Combat Action
- Challenge Rank

Suffer:
- Pay the Price
- Harm
- Stress
- Mystic Backlash
- Plot Twist

"Plot Twist" is a good choice to consult when e.g. failing a Fullfill a Vow move, so I think it fits "Suffer" tables.

**Comment by e4z9** [comment]
Screenshot_1623783617
Screenshot_1623783630
Screenshot_1623783637

**Comment by stevesea** [comment]
That looks great!

**Comment by e4z9** [comment]
How do you want to proceed? Should I squash the commits into one?

**Comment by stevesea** [comment]
I need to do some testing before pushing a new version out to Google Play. But, I think it's fine to merge now.

**Comment by e4z9** [comment]
Thanks! 👍

**Pull request merged**
